//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class sorteo
    {
        public sorteo()
        {
            this.premio = new HashSet<premio>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string titulo { get; set; }
    
        public virtual ICollection<premio> premio { get; set; }
    }
}
